# Generated by Django 6.0.4 on 2026-05-03 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asin', '-created_at'], name='api_analysi_asin_824b57_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(db_index=True, max_length=10)),
                ('your_product_data', models.JSONField()),
                ('competitors_data', models.JSONField()),
                ('analysis_text', models.TextField()),
                ('your_product_html', models.TextField()),
                ('competitor_1_html', models.TextField(blank=True)),
                ('competitor_2_html', models.TextField(blank=True)),
                ('competitor_3_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.analysistask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asin', '-created_at'], name='api_analysi_asin_7a4864_idx')],
            },
        ),
    ]
